# Generated by Django 3.0.4 on 2020-03-10 09:41

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_boardlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=boards.models.uploadto)),
                ('card_image_name', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Boardlist')),
            ],
        ),
    ]
