# Generated by Django 3.0.4 on 2020-03-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlist',
            old_name='archived',
            new_name='archive',
        ),
    ]
